export const NODE_ENV = 'NODE_ENV';

export const SERVER_PORT = 'SERVER_PORT';
export const API_GLOBAL_PREFIX = 'API_GLOBAL_PREFIX';

export const DB_HOST = 'DB_HOST';
export const DB_PORT = 'DB_PORT';
export const DB_USER = 'DB_USER';
export const DB_PASSWORD = 'DB_PASSWORD';
export const DB_DATABASE = 'DB_DATABASE';
export const DB_SYNCHRONIZE = 'DB_SYNCHRONIZE';

export const JWT_SECRET = 'JWT_SECRET';
export const JWT_RECOVERY_SECRET = 'JWT_RECOVERY_SECRET';
export const JWT_EXPIRES_IN_SECONDS = 'JWT_EXPIRES_IN_SECONDS';
export const JWT_RECOVERY_EXPIRES_IN_SECONDS =
  'JWT_RECOVERY_EXPIRES_IN_SECONDS';

export const COOKIE_SECURE = 'COOKIE_SECURE';
export const COOKIE_MAX_AGE_SECONDS = 'COOKIE_MAX_AGE_SECONDS';

export const FRONTEND_URL = 'FRONTEND_URL';

export const BCRYPT_SALT_ROUNDS = 'BCRYPT_SALT_ROUNDS';
export const MAX_LOGIN_ATTEMPTS = 'MAX_LOGIN_ATTEMPTS';
export const LOGIN_BLOCK_MINUTES = 'LOGIN_BLOCK_MINUTES';

export const TOKEN_EXPIRES_MINUTES = 'TOKEN_EXPIRES_MINUTES';
export const TOKEN_MAX_ATTEMPTS = 'TOKEN_MAX_ATTEMPTS';

export const MAIL_HOST = 'MAIL_HOST';
export const MAIL_PORT = 'MAIL_PORT';
export const MAIL_USER = 'MAIL_USER';
export const MAIL_PASSWORD = 'MAIL_PASSWORD';
export const MAIL_FROM = 'MAIL_FROM';

export const ADMIN_NOMBRE = 'ADMIN_NOMBRE';
export const ADMIN_APELLIDO = 'ADMIN_APELLIDO';
export const ADMIN_EMAIL = 'ADMIN_EMAIL';
export const ADMIN_PASSWORD = 'ADMIN_PASSWORD';
export const ADMIN_TELEFONO = 'ADMIN_TELEFONO';
